SELECT CAST(SUM(TIV_2016) AS DECIMAL(10,2)) AS TIV_2016 FROM insurance
  WHERE TIV_2015 IN

  (SELECT TIV_2015 FROM
    (SELECT TIV_2015, COUNT(*) as cnt FROM insurance GROUP BY TIV_2015) AS t1
    WHERE cnt > 1)
  
  AND (LAT, LON) NOT IN

  (SELECT LAT, LON FROM
  (SELECT LAT, LON, COUNT(*) as cnt FROM insurance GROUP BY LAT, LON) AS t2
  WHERE cnt > 1);
